**Метод Гаусса**

In [1]:
import numpy as np

In [2]:
def print_matrix(M, precision=2, augmented=False):
    n_cols = M.shape[1]
    for row in M:
        if augmented:
            print(' '.join([f"{x:6.{precision}f}" for x in row[:-1]]), end='')
            print(' |', end='')
            print(f"{row[-1]:6.{precision}f}")
        else:
            print(' '.join([f"{x:6.{precision}f}" for x in row]))

In [3]:
A = np.random.randint(-9, 10, (4, 4))
b = np.random.randint(-9, 10, 4)

print("Початкова система:")
print("Матриця A:")
print_matrix(A)
print("\nВектор b:")
print(b)
print("\nРозширена матриця системи:")
augmented = np.column_stack((A, b))
print_matrix(augmented, augmented=True)

Початкова система:
Матриця A:
  4.00   2.00   4.00  -1.00
 -9.00   0.00  -7.00  -6.00
 -5.00  -5.00  -7.00  -3.00
  9.00  -3.00  -4.00  -4.00

Вектор b:
[-7 -8 -5  7]

Розширена матриця системи:
  4.00   2.00   4.00  -1.00 | -7.00
 -9.00   0.00  -7.00  -6.00 | -8.00
 -5.00  -5.00  -7.00  -3.00 | -5.00
  9.00  -3.00  -4.00  -4.00 |  7.00


In [4]:
n = len(A)
current_matrix = augmented.copy().astype(float)

det = 1.0
inverse_augmented = np.column_stack((A, np.eye(n))).astype(float)

In [5]:
#Прямий хід
for k in range(n):
    print(f"\nКрок {k + 1}:")
    max_row = k + np.argmax(np.abs(current_matrix[k:, k]))
    
    # Матриця перестановки P_k
    P = np.eye(n)
    if max_row != k:
        P[[k, max_row]] = P[[max_row, k]]
        print(f"\nМатриця перестановки P_{k+1}:")
        print_matrix(P)
        current_matrix[[k, max_row]] = current_matrix[[max_row, k]]
        inverse_augmented[[k, max_row]] = inverse_augmented[[max_row, k]]
        det *= -1  # Зміна знаку визначника при перестановці рядків
        print(f"\nМатриця P_{k+1}A_{k}:")
        print_matrix(current_matrix, augmented=True)
    else:
        print(f"\nПерестановка не потрібна, P_{k+1} = I")
        print_matrix(P)
    
    # Матриця виключення M_k
    M = np.eye(n)
    print(f"\nРозрахунок елементів матриці виключення M_{k+1}:")
    for i in range(k + 1, n):
        if current_matrix[k, k] != 0:
            element = -current_matrix[i, k] / current_matrix[k, k]
            print(f"M_{i+1}{k+1} = -a_{i+1}{k+1}/a_{k+1}{k+1} = -({current_matrix[i, k]:.2f})/({current_matrix[k, k]:.2f}) = {element:.2f}")
            M[i, k] = element
    
    print(f"\nМатриця виключення M_{k+1}:")
    print_matrix(M)
    
    # Застосування матриці виключення
    current_matrix = M @ current_matrix
    inverse_augmented = M @ inverse_augmented
    print(f"\nМатриця A_{k+1} = M_{k+1}P_{k+1}A_{k}:")
    print_matrix(current_matrix, augmented=True)

    # Множимо діагональні елементи для визначника
    det *= current_matrix[k, k]


Крок 1:

Матриця перестановки P_1:
  0.00   1.00   0.00   0.00
  1.00   0.00   0.00   0.00
  0.00   0.00   1.00   0.00
  0.00   0.00   0.00   1.00

Матриця P_1A_0:
 -9.00   0.00  -7.00  -6.00 | -8.00
  4.00   2.00   4.00  -1.00 | -7.00
 -5.00  -5.00  -7.00  -3.00 | -5.00
  9.00  -3.00  -4.00  -4.00 |  7.00

Розрахунок елементів матриці виключення M_1:
M_21 = -a_21/a_11 = -(4.00)/(-9.00) = 0.44
M_31 = -a_31/a_11 = -(-5.00)/(-9.00) = -0.56
M_41 = -a_41/a_11 = -(9.00)/(-9.00) = 1.00

Матриця виключення M_1:
  1.00   0.00   0.00   0.00
  0.44   1.00   0.00   0.00
 -0.56   0.00   1.00   0.00
  1.00   0.00   0.00   1.00

Матриця A_1 = M_1P_1A_0:
 -9.00   0.00  -7.00  -6.00 | -8.00
  0.00   2.00   0.89  -3.67 |-10.56
  0.00  -5.00  -3.11   0.33 | -0.56
  0.00  -3.00 -11.00 -10.00 | -1.00

Крок 2:

Матриця перестановки P_2:
  1.00   0.00   0.00   0.00
  0.00   0.00   1.00   0.00
  0.00   1.00   0.00   0.00
  0.00   0.00   0.00   1.00

Матриця P_2A_1:
 -9.00   0.00  -7.00  -6.00 | -8.00
  0.00

In [6]:
# Зворотній хід для системи рівнянь
print("\nЗворотній хід:")
x = np.zeros(n)
for i in range(n-1, -1, -1):
    x[i] = (current_matrix[i, -1] - np.sum(current_matrix[i, i+1:-1] * x[i+1:])) / current_matrix[i, i]
    print(f"x_{i+1} = {x[i]:.2f}")

print("\nРозв'язок системи:")
print(x)

# Обчислення визначника
print("\nВизначник матриці A:")
print(f"det(A) = {det:.2f}")

# Зворотній хід для оберненої матриці
inverse = np.zeros((n, n))
for i in range(n-1, -1, -1):
    for j in range(n):
        inverse[i, j] = (inverse_augmented[i, n+j] - 
                        np.sum(current_matrix[i, i+1:n] * inverse[i+1:, j])) / current_matrix[i, i]

print("\nОбернена матриця A^(-1):")
print_matrix(inverse)

# Перевірка правильності обчислення оберненої матриці
print("\nПеревірка: A * A^(-1) повинна дати одиничну матрицю:")
result = np.round(A @ inverse, decimals=10)  # Округлення для уникнення помилок обчислення
print_matrix(result)


Зворотній хід:
x_4 = 3.43
x_3 = -3.76
x_2 = 2.68
x_1 = 1.52

Розв'язок системи:
[ 1.52443755  2.67649341 -3.75562452  3.42823894]

Визначник матриці A:
det(A) = -1289.00

Обернена матриця A^(-1):
 -0.06  -0.01  -0.08   0.09
 -0.24   0.16  -0.34   0.08
  0.36  -0.09   0.22  -0.12
 -0.32  -0.05  -0.13   0.01

Перевірка: A * A^(-1) повинна дати одиничну матрицю:
  1.00   0.00   0.00   0.00
  0.00   1.00  -0.00  -0.00
 -0.00   0.00   1.00  -0.00
 -0.00  -0.00   0.00   1.00


In [7]:
def print_matrix1(M, precision=2, augmented=False):
    n_cols = M.shape[1]
    for row in M:
        if augmented:
            print(' '.join([f"{x:6.{precision}f}" for x in row[:n_cols//2]]), end='')
            print(' |', end='')
            print(' '.join([f"{x:6.{precision}f}" for x in row[n_cols//2:]]))
        else:
            print(' '.join([f"{x:6.{precision}f}" for x in row]))

In [8]:
n = len(A)
# Створюємо розширену матрицю [A|I] для знаходження оберненої
I = np.eye(n)
inverse_augmented = np.column_stack((A, I)).astype(float)
print("\nРозширена матриця [A|I] для знаходження оберненої матриці:")
print_matrix1(inverse_augmented, augmented=True)

det = 1.0
current_matrix = inverse_augmented.copy()


Розширена матриця [A|I] для знаходження оберненої матриці:
  4.00   2.00   4.00  -1.00 |  1.00   0.00   0.00   0.00
 -9.00   0.00  -7.00  -6.00 |  0.00   1.00   0.00   0.00
 -5.00  -5.00  -7.00  -3.00 |  0.00   0.00   1.00   0.00
  9.00  -3.00  -4.00  -4.00 |  0.00   0.00   0.00   1.00


In [9]:
# Прямий хід
print("\nПРЯМИЙ ХІД:")
for k in range(n):
    print(f"\nКрок {k + 1}:")
    
    # Пошук головного елемента у стовпчику
    max_row = k + np.argmax(np.abs(current_matrix[k:, k]))
    
    # Матриця перестановки P_k
    P = np.eye(n)
    if max_row != k:
        P[[k, max_row]] = P[[max_row, k]]
        print(f"\nМатриця перестановки P_{k+1}:")
        print_matrix1(P)
        current_matrix[[k, max_row]] = current_matrix[[max_row, k]]
        det *= -1  # Зміна знаку визначника при перестановці рядків
        print(f"\nМатриця після застосування P_{k+1}:")
        print_matrix1(current_matrix, augmented=True)
    else:
        print(f"\nПерестановка не потрібна, P_{k+1} = I")
        print_matrix1(P)
    
    # Матриця виключення M_k
    M = np.eye(n)
    print(f"\nРозрахунок елементів матриці виключення M_{k+1}:")
    for i in range(k + 1, n):
        if current_matrix[k, k] != 0:
            element = -current_matrix[i, k] / current_matrix[k, k]
            print(f"M_{i+1}{k+1} = -a_{i+1}{k+1}/a_{k+1}{k+1} = -({current_matrix[i, k]:.2f})/({current_matrix[k, k]:.2f}) = {element:.2f}")
            M[i, k] = element
    
    print(f"\nМатриця виключення M_{k+1}:")
    print_matrix1(M)
    
    # Застосування матриці виключення
    current_matrix = M @ current_matrix
    print(f"\nМатриця після застосування M_{k+1}:")
    print_matrix1(current_matrix, augmented=True)
    
    # Множимо на діагональний елемент для визначника
    det *= current_matrix[k, k]

print("\nМатриця після прямого ходу:")
print_matrix1(current_matrix, augmented=True)


ПРЯМИЙ ХІД:

Крок 1:

Матриця перестановки P_1:
  0.00   1.00   0.00   0.00
  1.00   0.00   0.00   0.00
  0.00   0.00   1.00   0.00
  0.00   0.00   0.00   1.00

Матриця після застосування P_1:
 -9.00   0.00  -7.00  -6.00 |  0.00   1.00   0.00   0.00
  4.00   2.00   4.00  -1.00 |  1.00   0.00   0.00   0.00
 -5.00  -5.00  -7.00  -3.00 |  0.00   0.00   1.00   0.00
  9.00  -3.00  -4.00  -4.00 |  0.00   0.00   0.00   1.00

Розрахунок елементів матриці виключення M_1:
M_21 = -a_21/a_11 = -(4.00)/(-9.00) = 0.44
M_31 = -a_31/a_11 = -(-5.00)/(-9.00) = -0.56
M_41 = -a_41/a_11 = -(9.00)/(-9.00) = 1.00

Матриця виключення M_1:
  1.00   0.00   0.00   0.00
  0.44   1.00   0.00   0.00
 -0.56   0.00   1.00   0.00
  1.00   0.00   0.00   1.00

Матриця після застосування M_1:
 -9.00   0.00  -7.00  -6.00 |  0.00   1.00   0.00   0.00
  0.00   2.00   0.89  -3.67 |  1.00   0.44   0.00   0.00
  0.00  -5.00  -3.11   0.33 |  0.00  -0.56   1.00   0.00
  0.00  -3.00 -11.00 -10.00 |  0.00   1.00   0.00   1.00

Кр

In [10]:
# Зворотній хід
print("\nЗВОРОТНІЙ ХІД:")
for k in range(n-1, -1, -1):
    # Нормалізація діагонального елемента
    if current_matrix[k, k] != 0:
        factor = 1.0 / current_matrix[k, k]
        print(f"\nНормалізація {k+1}-го рядка (множимо на {factor:.2f}):")
        current_matrix[k] *= factor
        print_matrix1(current_matrix, augmented=True)
    
    # Матриця виключення для зворотного ходу
    M = np.eye(n)
    print(f"\nРозрахунок елементів матриці виключення для зворотного ходу:")
    for i in range(k):
        element = -current_matrix[i, k]
        print(f"M_{i+1}{k+1} = -a_{i+1}{k+1} = -({current_matrix[i, k]:.2f}) = {element:.2f}")
        M[i, k] = element
    
    print(f"\nМатриця виключення:")
    print_matrix1(M)
    
    # Застосування матриці виключення
    current_matrix = M @ current_matrix
    print(f"\nМатриця після виключення:")
    print_matrix1(current_matrix, augmented=True)

print("\nВизначник матриці A:")
print(f"det(A) = {det:.2f}")

print("\nОбернена матриця A^(-1):")
inverse = current_matrix[:, n:]
print_matrix1(inverse)

print("\nПеревірка: A * A^(-1) повинна дати одиничну матрицю:")
result = np.round(A @ inverse, decimals=10)
print_matrix1(result)

# Перевірка точності обчислень
print("\nПохибка обчислень:")
error = np.max(np.abs(result - np.eye(n)))
print(f"Максимальне відхилення від одиничної матриці: {error:.2e}")


ЗВОРОТНІЙ ХІД:

Нормалізація 4-го рядка (множимо на -0.32):
 -9.00   0.00  -7.00  -6.00 |  0.00   1.00   0.00   0.00
  0.00  -5.00  -3.11   0.33 |  0.00  -0.56   1.00   0.00
  0.00   0.00  -9.13 -10.20 |  0.00   1.33  -0.60   1.00
 -0.00  -0.00  -0.00   1.00 | -0.32  -0.05  -0.13   0.01

Розрахунок елементів матриці виключення для зворотного ходу:
M_14 = -a_14 = -(-6.00) = 6.00
M_24 = -a_24 = -(0.33) = -0.33
M_34 = -a_34 = -(-10.20) = 10.20

Матриця виключення:
  1.00   0.00   0.00   6.00
  0.00   1.00   0.00  -0.33
  0.00   0.00   1.00  10.20
  0.00   0.00   0.00   1.00

Матриця після виключення:
 -9.00   0.00  -7.00   0.00 | -1.91   0.67  -0.81   0.07
  0.00  -5.00  -3.11   0.00 |  0.11  -0.54   1.04  -0.00
  0.00   0.00  -9.13   0.00 | -3.25   0.78  -1.98   1.13
  0.00   0.00   0.00   1.00 | -0.32  -0.05  -0.13   0.01

Нормалізація 3-го рядка (множимо на -0.11):
 -9.00   0.00  -7.00   0.00 | -1.91   0.67  -0.81   0.07
  0.00  -5.00  -3.11   0.00 |  0.11  -0.54   1.04  -0.00
 -0.00 

**Метож прогонки**

In [11]:
def generate_tridiagonal_matrix(n):
    c = np.zeros(n+1)      
    a = np.zeros(n+1)      
    b = np.zeros(n+1)     
    
    for i in range(1, n+1):
        if i < n:
            b[i] = np.random.randint(-9, 9)  # Змінено на (-9, 9)
        if i > 1:
            a[i] = np.random.randint(-9, 9)  # Змінено на (-9, 9)
    
    for i in range(1, n+1):
        sum_of_elements = 0
        if i > 1:
            sum_of_elements += abs(a[i])
        if i < n:
            sum_of_elements += abs(b[i])
        sign = np.random.choice([-1, 1])
        c[i] = sign * (sum_of_elements + np.random.randint(1, 4))
    
    f = np.zeros(n+1)
    for i in range(1, n+1):
        f[i] = np.random.randint(-9, 9)  # Змінено на (-9, 9)
    
    matrix = np.zeros((n+1, n+1))
    for i in range(1, n+1):
        matrix[i][i] = c[i]
        if i > 1:
            matrix[i][i-1] = a[i]
        if i < n:
            matrix[i][i+1] = b[i]
    
    return a, b, c, f, matrix

In [12]:
def format_number_in_equation(num):
    return f"({num:.4f})" if num < 0 else f"{num:.4f}"

def format_number_after_equals(num):
    return f"{num:.4f}"

In [13]:

def thomas_algorithm(a, b, c, f, n):
    print("\nДетальні обчислення методу прогонки:")
    print("=====================================")
    
    a, b, c, f = tuple(map(lambda k_list: list(map(float, k_list)), (a, b, c, f)))
    alpha = [0] * (n+1)
    beta = [0] * (n+1)
    x = [0] * (n+1)

    # Прямий хід
    print("\nПрямий хід:")
    print("----------")
    
    # Початкові значення
    alpha[1] = -b[1] / c[1]
    beta[1] = f[1] / c[1]
    print(f"i = 1:")
    print(f"α₁ = -b₁/c₁ = -({format_number_in_equation(b[1])})/({format_number_in_equation(c[1])}) = {format_number_after_equals(alpha[1])}")
    print(f"β₁ = f₁/c₁ = {format_number_in_equation(f[1])}/{format_number_in_equation(c[1])} = {format_number_after_equals(beta[1])}")

    for i in range(2, n+1):
        denominator = a[i]*alpha[i-1] + c[i]
        alpha[i] = -b[i]/denominator
        beta[i] = (f[i] - a[i]*beta[i-1])/denominator
        
        print(f"\ni = {i}:")
        print(f"Знаменник = a{i}·α{i-1} + c{i} = {format_number_in_equation(a[i])}·{format_number_in_equation(alpha[i-1])} + {format_number_in_equation(c[i])} = {format_number_after_equals(denominator)}")
        print(f"α{i} = -b{i}/знаменник = -({format_number_in_equation(b[i])})/({format_number_in_equation(denominator)}) = {format_number_after_equals(alpha[i])}")
        print(f"β{i} = (f{i} - a{i}·β{i-1})/знаменник = ({format_number_in_equation(f[i])} - {format_number_in_equation(a[i])}·{format_number_in_equation(beta[i-1])})/{format_number_in_equation(denominator)} = {format_number_after_equals(beta[i])}")

    # Зворотний хід
    print("\nЗворотний хід:")
    print("-------------")
    x[n] = beta[n]
    print(f"x{n} = β{n} = {format_number_after_equals(x[n])}")
    
    for i in range(n-1, 0, -1):
        x[i] = alpha[i]*x[i+1] + beta[i]
        print(f"x{i} = α{i}·x{i+1} + β{i} = {format_number_in_equation(alpha[i])}·{format_number_in_equation(x[i+1])} + {format_number_in_equation(beta[i])} = {format_number_after_equals(x[i])}")
    
    return x[1:n+1]



In [14]:
n = 4  # Розмір матриці 4x4
a, b, c, f, matrix = generate_tridiagonal_matrix(n)
print("Згенерована матриця:")
print(matrix[1:n+1, 1:n+1])
print("\nЗгенеровані діагоналі матриці:")
print("Нижня діагональ (a):", a[1:n+1])
print("Верхня діагональ (b):", b[1:n+1])
print("Головна діагональ (c):", c[1:n+1])
print("\nВектор правої частини (f):", f[1:n+1])

# Розв'язуємо систему
print("\nРозв'язування системи:")
print("Ax = f, де")
print("A =")
print(matrix[1:n+1, 1:n+1])
print("f =", f[1:n+1])
solution = thomas_algorithm(a, b, c, f, n)
print("\nФінальний розв'язок x =", solution)

Згенерована матриця:
[[-6.  4.  0.  0.]
 [ 2. -8.  4.  0.]
 [ 0. -8. 16. -6.]
 [ 0.  0.  7. -9.]]

Згенеровані діагоналі матриці:
Нижня діагональ (a): [ 0.  2. -8.  7.]
Верхня діагональ (b): [ 4.  4. -6.  0.]
Головна діагональ (c): [-6. -8. 16. -9.]

Вектор правої частини (f): [ 3. -5.  8. -4.]

Розв'язування системи:
Ax = f, де
A =
[[-6.  4.  0.  0.]
 [ 2. -8.  4.  0.]
 [ 0. -8. 16. -6.]
 [ 0.  0.  7. -9.]]
f = [ 3. -5.  8. -4.]

Детальні обчислення методу прогонки:

Прямий хід:
----------
i = 1:
α₁ = -b₁/c₁ = -(4.0000)/((-6.0000)) = 0.6667
β₁ = f₁/c₁ = 3.0000/(-6.0000) = -0.5000

i = 2:
Знаменник = a2·α1 + c2 = 2.0000·0.6667 + (-8.0000) = -6.6667
α2 = -b2/знаменник = -(4.0000)/((-6.6667)) = 0.6000
β2 = (f2 - a2·β1)/знаменник = ((-5.0000) - 2.0000·(-0.5000))/(-6.6667) = 0.6000

i = 3:
Знаменник = a3·α2 + c3 = (-8.0000)·0.6000 + 16.0000 = 11.2000
α3 = -b3/знаменник = -((-6.0000))/(11.2000) = 0.5357
β3 = (f3 - a3·β2)/знаменник = (8.0000 - (-8.0000)·0.6000)/11.2000 = 1.1429

i = 4:
Знаме

Метод Зейделя

In [15]:
def generate_matrix_and_vector(n=4):

    while True:
        A = np.zeros((n, n))
        for i in range(n):
            for j in range(i+1, n):
                A[i][j] = np.random.randint(-2, 3)  

        A = A + A.T
        valid_matrix = True
        for i in range(n):
            row_sum = np.sum(np.abs(A[i])) - np.abs(A[i][i])
            if row_sum >= 9:
                valid_matrix = False
                break
                
            # Встановлюємо діагональний елемент більшим за суму модулів
            A[i][i] = row_sum + np.random.randint(1, min(4, 9-row_sum))
            # Випадково змінюємо знак діагонального елемента
            if np.random.random() < 0.5:
                A[i][i] *= -1
        
        if valid_matrix:
            break
    
    # Генеруємо вектор вільних членів
    b = np.random.randint(-9, 9, size=n)
    
    return A, b



In [16]:
def seidel_method(matrix, constants, epsilon=1e-4, show_iterations=True):
    """
    Реалізує метод Зейделя для розв'язання системи лінійних рівнянь.
    Використовує формулу: x_i^(k+1) = sum(c_ij * x_j^(k+1)) + sum(c_ij * x_j^(k)) + d_i
    """
    n = len(matrix)
    x = np.zeros(n)  # Початкове наближення
    x_prev = np.zeros(n)  # Попереднє наближення
    iteration_count = 0
    
    # Попередньо обчислюємо коефіцієнти c_ij та d_i
    c = np.zeros((n, n))
    d = np.zeros(n)
    
    for i in range(n):
        for j in range(n):
            if i != j:
                c[i][j] = -matrix[i][j] / matrix[i][i]
        d[i] = constants[i] / matrix[i][i]
    
    while True:
        x_prev = x.copy()
        
        if show_iterations:
            print(f"\nІтерація {iteration_count + 1}:")
            print("-" * 60)
        
        for i in range(n):
            # Перша сума (використовує оновлені значення)
            sum1 = sum(c[i][j] * x[j] for j in range(i))
            
            # Друга сума (використовує попередні значення)
            sum2 = sum(c[i][j] * x_prev[j] for j in range(i + 1, n))
            
            # Нове значення x_i
            x[i] = sum1 + sum2 + d[i]
            
            if show_iterations:
                print(f"x_{i+1}^({iteration_count + 1}):")
                print(f"1) Перша сума = {sum1:.6f} (sum(c_{i+1}j * x_j^({iteration_count + 1})) для j=1...{i})")
                print(f"2) Друга сума = {sum2:.6f} (sum(c_{i+1}j * x_j^({iteration_count})) для j={i+2}...{n})")
                print(f"3) d_{i+1} = {d[i]:.6f}")
                print(f"4) x_{i+1} = {sum1:.6f} + {sum2:.6f} + {d[i]:.6f} = {x[i]:.6f}")
                print("-" * 40)
        
        # Обчислюємо похибку
        error = np.max(np.abs(x - x_prev))
        
        if show_iterations:
            print(f"Похибка на ітерації: {error:.9f}")
            print("-" * 60)
        
        iteration_count += 1
        
        if error < epsilon:
            break
    
    print("\nФінальні результати:")
    print(f"Кількість ітерацій: {iteration_count}")
    for i in range(n):
        print(f"x_{i+1} = {x[i]:.9f}")
    
    return x

In [17]:
n = 4
A, b = generate_matrix_and_vector(n)

print("Згенерована матриця A:")
print(A)
# Перевіряємо симетричність
print("\nМатриця симетрична:", np.allclose(A, A.T))

# Перевіряємо діагональну перевагу
diagonal_dominance = all(abs(A[i][i]) >= sum(abs(A[i][j]) for j in range(n) if i != j) for i in range(n))
print("Діагональна перевага виконується:", diagonal_dominance)

print("\nЗгенерований вектор b:")
print(b)

print("\nРозв'язання системи методом Зейделя:")
solution = seidel_method(A, b, epsilon=1e-4, show_iterations=True)

# Перевірка розв'язку
print("\nПеревірка розв'язку:")
residual = np.dot(A, solution) - b
print("Нев'язка:")
print(residual)
print("Норма нев'язки:", np.linalg.norm(residual))

Згенерована матриця A:
[[ 5. -2. -1.  0.]
 [-2.  8. -2.  1.]
 [-1. -2.  6.  2.]
 [ 0.  1.  2.  4.]]

Матриця симетрична: True
Діагональна перевага виконується: True

Згенерований вектор b:
[ 1 -6 -8  1]

Розв'язання системи методом Зейделя:

Ітерація 1:
------------------------------------------------------------
x_1^(1):
1) Перша сума = 0.000000 (sum(c_1j * x_j^(1)) для j=1...0)
2) Друга сума = 0.000000 (sum(c_1j * x_j^(0)) для j=2...4)
3) d_1 = 0.200000
4) x_1 = 0.000000 + 0.000000 + 0.200000 = 0.200000
----------------------------------------
x_2^(1):
1) Перша сума = 0.050000 (sum(c_2j * x_j^(1)) для j=1...1)
2) Друга сума = 0.000000 (sum(c_2j * x_j^(0)) для j=3...4)
3) d_2 = -0.750000
4) x_2 = 0.050000 + 0.000000 + -0.750000 = -0.700000
----------------------------------------
x_3^(1):
1) Перша сума = -0.200000 (sum(c_3j * x_j^(1)) для j=1...2)
2) Друга сума = 0.000000 (sum(c_3j * x_j^(0)) для j=4...4)
3) d_3 = -1.333333
4) x_3 = -0.200000 + 0.000000 + -1.333333 = -1.533333
-------